server:
  port: 8081
  servlet:
    context-path: /
    session:
      timeout: PT60M
spring:
  security:
    user:
      name: forlos
      password: 123
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: HikariCPDatasource
    password: 123456
    url: jdbc:mysql://localhost:3306/hoel_cs_appman_sys?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
  web:
    resources:
      add-mappings: false
## logback配置
logging:
  level:
    org:
      springframework:
        security: debug
redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  timeout: 60000
  ssl: false
  jedis:
    pool:
      max-active: 50
      max-idle: 30
      min-idle: 10
      max-wait: 3000
      test-on-borrow: true
